<?php
/**
 * Migration: Create app_notifications table
 * Internal notifications generated by the app for user-specific events.
 * Separate from platform_notifications (owner broadcasts).
 */
require_once __DIR__ . '/../config/db.php';

$pdo->exec("
    CREATE TABLE IF NOT EXISTS app_notifications (
        id INT AUTO_INCREMENT PRIMARY KEY,
        company_id INT NOT NULL,
        user_id INT NOT NULL COMMENT 'Target user who should see this notification',
        title VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        type ENUM('info','warning','success','alert') DEFAULT 'info',
        link VARCHAR(500) NULL COMMENT 'Optional page link (e.g. requisitions.php)',
        is_read TINYINT(1) DEFAULT 0,
        read_at DATETIME NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_user_unread (user_id, is_read, created_at),
        INDEX idx_company (company_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
");

echo "app_notifications table created.\n";
?>
